In [2]:
import numpy as np

In [3]:
A = np.array([
    [0,1,-1],
    [-1,-3,2],
    [2,1,1]])

B = np.array([
    [-4,-1,2],
    [3,-4,-5],
    [-5,-2,2]
])

b = np.array([1,2,5])

# A

In [4]:
AB = np.dot(A,B)
print(AB)

[[  8  -2  -7]
 [-15   9  17]
 [-10  -8   1]]


# B

In [5]:
det_a = np.linalg.det(A)
det_b = np.linalg.det(B)
print(det_a, det_b)

2.775557561562896e-16 1.0000000000000022


# C

In [6]:
print(np.linalg.det(AB))

3.613775945154876e-14


# D

In [7]:
inv_B = np.linalg.inv(B)
x = inv_B @ b

In [8]:
x

array([ 43., -47.,  63.])

In [9]:
B@x

array([1., 2., 5.])

### A has either inf solutions or no solutions, need to find out

# 1.2

# A

In [22]:
b.T*A*b

array([[  0,   4, -25],
       [ -1, -12,  50],
       [  2,   4,  25]])

In [23]:
A

array([[ 0,  1, -1],
       [-1, -3,  2],
       [ 2,  1,  1]])

In [24]:
A[1][0]

-1

In [24]:
c = 1/10**5
i = 1 - c
ci = 1/10**6
cc = 0.8
ii = 1 - ci
ic = 1 - cc


In [26]:
i*ii + c*ic + i*ci + c*cc

1.0

In [9]:
c*1.0

1e-05

In [12]:
cc

0.8

In [13]:
c

1e-05

In [29]:
cc*c + ci * i + ic * c + ii * i

1.0

In [18]:
1/10**6 * (1-1/10**5) + 0.8 * 1/10**5

8.99999e-06

In [43]:
up = 0.2 * (1/10**5)
down = 1 - (9*10**(-6))

In [44]:
up/down

2.000018000162002e-06

In [45]:
0.889 * 9 * 10**(-6) + 2 * 10**(-6) * (1 - 9 * 10**(-6))

1.0000981999999999e-05